name: Data Quality Pipeline
on: [push, pull_request]

jobs:
  dq-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.3'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Dependencies
        run: uv sync

      - name: Generate mock data
        run: uv run tests/generate_data.py

      - name: Run tests
        run: uv run pytest tests/test_data_quality.py

      - name: Generate report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dq-failure-report
          path: |
            processed_users.csv
            .pytest-cache/
          retention-days: 3